
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbigtrtcajmhkrbkgnhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiaWd0cnRjYWptaGtyYmtnbmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NzE4NzMsImV4cCI6MjA1NzQ0Nzg3M30.jezf2k7i-sfpRsH8CkuAJVklO7Zy2gPep9wbYeP7WG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
